name: Server - Rust build

on:
  push:
    # On main, it's the build and deploy that will run
    branches-ignore: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ./server
      run: sudo apt-get update; sudo apt-get install -y libusb-1.0-0-dev && cargo build --verbose
    - name: Run tests
      working-directory: ./server
      run: cargo test --verbose
